name: dict2229
description: a client for the RFC 2229 DICT protocol.
publish_to: 'none'
version: 0.2.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  settings_ui: ^1.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  backdrop: ^0.6.2
  application_icon: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
