name: dict2229
description: a client for the RFC 2229 DICT protocol.
publish_to: 'none'
version: 0.4.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  settings_ui: ^1.0.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  backdrop: ^0.6.2
  package_info_plus: ^1.0.4
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.9
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
