name: CI_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Get flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - name: flutter get deps
        run: flutter pub get

      - name: flutter test
        run: flutter test
